// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ProcessAPI.Models;
using System;

namespace ProcessAPI.Migrations
{
    [DbContext(typeof(ProcessContext))]
    [Migration("20171127195203_fixedstudentexamtable")]
    partial class fixedstudentexamtable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProcessAPI.Models.Exam", b =>
                {
                    b.Property<int>("ExamID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ExamName");

                    b.Property<int?>("StudentExamID");

                    b.HasKey("ExamID");

                    b.HasIndex("StudentExamID");

                    b.ToTable("Exam");
                });

            modelBuilder.Entity("ProcessAPI.Models.Process", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ExamName");

                    b.Property<int>("ExamNumber");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int>("ProcessID");

                    b.Property<string>("ProcessName");

                    b.Property<int>("StudentNumber");

                    b.Property<string>("TimeStamp");

                    b.Property<string>("WindowName");

                    b.HasKey("ID");

                    b.ToTable("Process");
                });

            modelBuilder.Entity("ProcessAPI.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int?>("StudentExamID");

                    b.Property<int>("StudentNumber");

                    b.Property<DateTime>("TimeStamp");

                    b.HasKey("StudentID");

                    b.HasIndex("StudentExamID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("ProcessAPI.Models.StudentExam", b =>
                {
                    b.Property<int>("StudentExamID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BaseURL");

                    b.Property<int>("ProcessID");

                    b.Property<string>("ProcessName");

                    b.HasKey("StudentExamID");

                    b.ToTable("StudentExam");
                });

            modelBuilder.Entity("ProcessAPI.Models.Exam", b =>
                {
                    b.HasOne("ProcessAPI.Models.StudentExam")
                        .WithMany("ExamID")
                        .HasForeignKey("StudentExamID");
                });

            modelBuilder.Entity("ProcessAPI.Models.Student", b =>
                {
                    b.HasOne("ProcessAPI.Models.StudentExam")
                        .WithMany("StudentID")
                        .HasForeignKey("StudentExamID");
                });
#pragma warning restore 612, 618
        }
    }
}
